### ISSUE TITLE
Nuxt.js

### ISSUE THREAD

**Issue by DanielRuf** [open-mentoring/topics#33]

**Comment by MyIsaak** [comment]
I can present a talk about this.

**Comment by DanielRuf** [comment]
Cool =) I guess at Frontend Rhein-Neckar or RheinNeckarJS?

**Comment by MyIsaak** [comment]
Would make more sense at the RheinNeckarJS.

**Comment by MyIsaak** [comment]
Or Frontend? What is the difference?

**Comment by DanielRuf** [comment]
Probably Frontend Rhein-Neckar as it is more about frontend than JavaScript in general. 

We have a repo for the talk proposals at https://github.com/frontend-rhein-neckar/talk-proposals/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

Can yous submit yours there too? This makes it easier for us to have a better overview.
